### PR TITLE
#148227407 Create the Landing Page

### PR DESCRIPTION
**Pull request by Andela-Didacus**
#### What does this PR do?
- Setup sass loader for web pack
- Integrate React Router
- Create A landing page for the landing map product

#### Description of Task to be completed?
Add sass-loader to the web pack setup to enable the styling of components using sass.
Create the landing page component and the required styling components.
Setup and integrate react router. Then set up the landing page as the main page '/'.

#### How should this be manually tested?
After cloning the repository and installing the required dependencies using `yarn install`, run `npm test` to test.

#### Any background context you want to provide?
Initially there was no landing page, nor was there a routing or sass integration, This has been made available by this PR

#### What are the relevant pivotal tracker stories?
 
 [#148227407](https://www.pivotaltracker.com/story/show/148227407) 
 [#148680355](https://www.pivotaltracker.com/story/show/148680355)
 [#148684213](https://www.pivotaltracker.com/story/show/148684213)

#### Screenshots (if appropriate)
screen shot 2017-07-12 at 11 24 46 am

### CODE REVIEW

**Comment by andela-uofoegbu** [comment]
@Andela-Didacus 
Hey, Didah. Two things and a question
1. Your branch has conflits.
2. Screenshot is not showing on the PR message

Question: I'm not sure if that's part of your task but should there be a basic dropdown (with no functionality) when you click on the contribute button?

**Comment by andela-kakpobome** [comment]
Also please ensure the story IDs link to the actual stories on Pivotal, 🙇

**Comment by Andela-Didacus** [comment]
@andela-uofoegbu I was advised by Kes to only create the button not the drop down list. as for the screenshot not sure whats up because it shows on all the computers from others guys.   

@andela-kakpobome I do not understand what you mean. This PR covers three stories.

**Comment by andela-uofoegbu** [comment]
@Andela-Didacus I see it now. Thanks. Waiting for the conflicts to be resolved

**Comment by andela-kakpobome** [comment]
@Andela-Didacus [#148227407](https://www.pivotaltracker.com/story/show/148227407) instead of just **#148227407**

**Comment by Andela-Didacus** [comment]
@andela-kakpobome correction made.

**Comment by Andela-Didacus** [comment]
@andela-uofoegbu that can't e done on the title. He meant the 'What are the relevant pivotal tracker stories?' section.

**Pull request merged**
