### PR TITLE
#149223113 Add dropdown to landing page

### PR DESCRIPTION
**Pull request by andela-uofoegbu**
#### What does this PR do?
Adds a drop down to the landing page contribution button
#### Description of Task to be completed?
As a user, I should see a dropdown when I hover on the CONTRIBUTE button on the landing page
#### How should this be manually tested?
After cloning the repo, CD into the directory.
Run `yarn install`
Run `npm start`
Hover over the Contribute button
#### What are the relevant pivotal tracker stories?
[#149223113](https://www.pivotaltracker.com/n/projects/2059149/stories/149223113)
#### Screenshots (if appropriate)
screen shot 2017-07-20 at 14 52 29

### CODE REVIEW

**Comment by BolajiOlajide** [comment]
LGTM

**Comment by andela-kakpobome** [comment]
@andela-uofoegbu read through the engineering wiki, and properly format your commit messages. In particular, for feature branches, we use `feat` not `ft`.

**Comment by BolajiOlajide** [comment]
@andela-kakpobome According to the engineering wiki, we use `ft` for feature branches and not `feat`. We only use `feat` for commit messages. Please confirm.
screen shot 2017-07-21 at 10 34 13 am

**Comment by andela-kakpobome** [comment]
@BolajiOlajide you notice that I said to change `commit messages` not `branch names`?

**Comment by andela-uofoegbu** [comment]
@BolajiOlajide @andela-kakpobome 
Made the changes. Please review

**Pull request merged**
